# Generated by Django 5.1.1 on 2024-11-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='favorite',
        ),
    ]
