# Generated by Django 5.1.1 on 2024-11-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_remove_bookmark_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
